{{- if and .Values.backup.enabled .Values.backup.gcs.applicationCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-backup-gcs
type: Opaque
stringData:
  credentials.json: {{ .Values.backup.gcs.applicationCredentials | quote }}
{{- end }}
