version: "3"

vars:
  K8S_VERSION: v1.33.0

tasks:
  dev:start:
    cmds:
      - minikube start --kubernetes-version={{.K8S_VERSION}}
      - minikube addons enable ingress
      - minikube addons enable ingress-dns
      - task: set-context

  dev:stop:
    cmds:
      - minikube stop

  dev:reset:
    cmds:
      - minikube delete
      - task: reset:pipelines

  build:pipelines:
    cmds:
      - |
        eval $(minikube -p minikube docker-env)
        cd ../processing/services/pipelines && skaffold build || true

  build:superset:
    cmds:
      - |
        eval $(minikube -p minikube docker-env)
        cd ../processing/services/superset && skaffold build || true

  reset:pipelines:
    cmds:
      - |
        eval $(minikube -p minikube docker-env)
        cd ../processing/services/pipelines && skaffold delete

  reset:superset:
    cmds:
      - |
        eval $(minikube -p minikube docker-env)
        cd ../processing/services/superset && skaffold delete

  set-context:
    desc: Set kubectl default namespace to celine
    cmds:
      - kubectl config use-context minikube
      - kubectl config set-context --current --namespace=celine-dev

  helm:apply:*:
    vars:
      DEPLOYMENT_ENV: "{{ index .MATCH 0 }}"
      ARGS: "{{ .CLI_ARGS }}"
    env:
      SOPS_AGE_KEY_FILE: "{{ .PWD }}/.sops/{{ .DEPLOYMENT_ENV }}/key.txt"
    cmds:
      - |
        if [ -z "{{ .ARGS }}" ]; then
          echo "Error: missing filter argument (e.g. name=chart1)"
          exit 1
        fi
        helmfile -e {{ .DEPLOYMENT_ENV }} -l {{ .ARGS }} apply

  helm:destroy:*:
    vars:
      DEPLOYMENT_ENV: "{{ index .MATCH 0 }}"
      ARGS: "{{ .CLI_ARGS }}"
    env:
      SOPS_AGE_KEY_FILE: "{{ .PWD }}/.sops/{{ .DEPLOYMENT_ENV }}/key.txt"
    cmds:
      - |
        if [ -z "{{ .ARGS }}" ]; then
          echo "Error: missing filter argument (e.g. name=chart1)"
          exit 1
        fi
        helmfile -e {{ .DEPLOYMENT_ENV }} -l {{ .ARGS }} destroy

  apply:
    env:
      SOPS_AGE_KEY_FILE: "{{.PWD}}/.sops/{{.CLI_ARGS}}/key.txt"
    cmds:
      - |
        if [ ! -d "./envs/{{.CLI_ARGS}}" ]; then \
          echo "Environment ./envs/{{.CLI_ARGS}} not found"
          exit 1
        fi
      - helmfile -e {{.CLI_ARGS}} -l name=cnpg apply
      - helmfile -e {{.CLI_ARGS}} -l group=core apply
      - helmfile -e {{.CLI_ARGS}} -l group=auth apply
      - helmfile -e {{.CLI_ARGS}} -l group=apps apply
      - helmfile -e {{.CLI_ARGS}} -l group=pipelines apply

  apply:dev:
    deps:
      - sops:copy-dev-keys
      - set-context
      - build:pipelines
    cmds:
      - task apply -- dev

  mqtt:passwd:
    cmds:
      - |
        FILE=$(mktemp)
        mosquitto_passwd -H sha512-pbkdf2 -c $FILE USERNAME
        cut -d ":" -f 2 $FILE
        rm $FILE

  postgres:forward:
    cmds:
      - kubectl port-forward svc/postgis1-rw 5432:5432
  sops:encrypt:
    desc: Encrypt secrets.yaml -> secrets.sops.yaml (per-env key)
    cmds:
      - |
        set -e
        shopt -s nullglob
        for f in envs/*/secrets.yaml; do
          env=$(basename "$(dirname "$f")")
          key=".sops/$env/key.txt"
          out="${f%.yaml}.sops.yaml"

          if [ ! -f "$key" ]; then
            echo "Missing key for $env ($key), skipping"
            continue
          fi

          echo "Encrypting $f → $out"
          SOPS_AGE_KEY_FILE="$key" sops --encrypt "$f" > "$out"
        done
        shopt -u nullglob

  sops:decrypt:
    desc: Decrypt secrets.sops.yaml -> secrets.yaml (per-env key)
    cmds:
      - |
        set -e
        for f in envs/*/secrets.sops.yaml; do
          env=$(basename "$(dirname "$f")")
          key=".sops/$env/key.txt"
          out="${f%.sops.yaml}.yaml"

          if [ ! -f "$key" ]; then
            echo "Missing key for $env ($key), skipping"
            continue
          fi

          # --- Backup existing secrets.yaml if present ---
          if [ -f "$out" ]; then
            ts=$(date +"%Y%m%d%H%M")
            backup="${out}.${ts}"
            echo "Backing up existing $out -> $backup"
            cp "$out" "$backup"

            # Keep only last 5 backups
            backups=( $(ls -1t "${out}".20* 2>/dev/null || true) )
            if [ ${#backups[@]} -gt 5 ]; then
              to_delete=( "${backups[@]:5}" )
              echo "Pruning old backups:"
              for del in "${to_delete[@]}"; do
                echo "  removing $del"
                rm -f "$del"
              done
            fi
          fi


          echo "Decrypting $f → $out"
          SOPS_AGE_KEY_FILE="$key" sops --decrypt "$f" > "$out"
        done

  sops:create-env:
    desc: Create a new environment and AGE key (adds to .sops.yaml)
    cmds:
      - |
        set -e
        ENV={{.CLI_ARGS}}
        test -n "$ENV" || { echo "Usage: task sops:create-env <env>"; exit 1; }

        keydir=".sops/$ENV"
        keyfile="$keydir/key.txt"

        if [ -d "$keydir" ]; then
          echo "Environment '$ENV' already exists."
          exit 1
        fi

        mkdir -p "$keydir"
        age-keygen -o "$keyfile" > /dev/null

        # create stub folder
        mkdir -p "./envs/$ENV"
        SEC=./envs/$ENV/secrets.yaml
        if [ ! -f $SEC ]; then
          echo "---" > $SEC
          echo "Created stub secret $SEC"
        fi
        VAL=./envs/$ENV/values.yaml
        if [ ! -f $VAL ]; then
          cp ./envs/dev/values.yaml $VAL
          echo "Created stub file $VAL"
        fi

        pubkey=$(grep "public key" "$keyfile" | awk '{print $4}')
        echo "Public key for $ENV: $pubkey"

        touch .sops.yaml
        if ! grep -q "path_regex: envs/$ENV/secrets\\.ya" .sops.yaml 2>/dev/null; then
          printf "  - path_regex: envs/%s/secrets\\.ya?ml\$\n    age: %s\n" "$ENV" "$pubkey" >> .sops.yaml
        fi

        echo "Added creation rule for $ENV in .sops.yaml"

  sops:copy-dev-keys:
    desc: Copy dev sops keys
    cmds:
      - cp .sops/dev/key.txt.example .sops/dev/key.txt
      - |
        if [ ! -f .sops.yaml ]; then 
          cp .sops.example.yaml .sops.yaml
        fi
      - |
        if [ ! -f ./envs/dev/secrets.yaml ]; then 
          cat "---" > ./envs/dev/secrets.yaml
        fi
