apiVersion: v1
kind: Secret
metadata:
  name: prefect-pipelines-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  CELINE_OIDC_CLIENT_SECRET: {{ .Values.global.oidcClientSecret }}
