{{- $v := deepCopy .Values }}
{{- $_ := set $v "extraSecrets" (include "celine-onboarding.secretData" . | fromYaml) }}
{{ include "celine-services.secret" (dict "Values" $v "Release" .Release "Chart" .Chart "Capabilities" .Capabilities "Template" .Template) }}
